services:
  postgres:
    container_name: ${PG_CONTAINER_NAME}
    image: ${PG_IMAGE}:${PG_VERSION}
    environment:
      - POSTGRES_DB=${PG_DB}                 # The database name
      - POSTGRES_USER=${PG_USER}             # The PostgreSQL username
      - POSTGRES_PASSWORD=${PG_PASSWORD}     # The PostgreSQL password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ${PG_PATH}:/var/lib/postgresql/data

  #odoo_scripts:
    #container_name: ${ODOO_SCRIPTS_CONTAINER_NAME}
    #image: alpine:latest
    #volumes:
    #  - ${SCRIPT_PATH}:/scripts
    #command: /bin/sh -c "/scripts/pull_repos.sh && /scripts/active_modules.sh"
    #depends_on:
    #  - odoo

  odoo:
    container_name: ${ODOO_CONTAINER_NAME}
    image: ${ODOO_IMAGE}:${ODOO_VERSION}
    #build: versions/13.0/.
    restart: unless-stopped
    entrypoint: ["/scripts/entrypoint.sh"]
    #command: ["odoo", "-i", "base", "-d", "odoo", "--db-filter=odoo"]
    #links:
    #  - postgres:db
    depends_on:
      - postgres
    ports:
      - ${ODOO_PORT}:8069
    volumes:
      - ./entrypoint.sh:/scripts/entrypoint.sh  # Monta entrypoint.sh en el contenedor
      - ./modulos.txt:/scripts/modulos.txt      # Monta modulos.txt en el contenedor
      - ${CONF_PATH}:/opt/etc/odoo
      - ${DATA_PATH}:/opt/odoo/data
      - ${LOG_PATH}:/var/log/odoo
      - ${CUSTOM_ADDONS}:/mnt/extra-addons
      - ${SCRIPT_PATH}:/scripts
      - ${FILE_PATH}:/var/lib/odoo
      #- ${BASE_DIR_PROD}${PROJECT_PATH}/backup_dir:/var/odoo/backups/
    environment:
      - HOST=postgres
      #- USER=odoo
      #- PASSWORD=odoo
      - CUSTOM_ADDONS=${CUSTOM_ADDONS}
      - MAIN_MODULE=${MAIN_MODULE}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
