networks:
  odoo:
  
services:
  postgres:
    #container_name: ${PG_CONTAINER_NAME}
    image: ${PG_IMAGE}:${PG_VERSION}
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ${PG_PATH}:/var/lib/postgresql/data
    networks:
      - odoo

  odoo:
    #container_name: ${ODOO_CONTAINER_NAME}
    #image: ${ODOO_IMAGE}:${ODOO_VERSION}
    build: versions/16.0/.
    restart: unless-stopped
    entrypoint: ["/scripts/entrypoint.sh"]
    depends_on:
      - postgres
    ports:
      - ${ODOO_PORT}:8069
    volumes:
      - ./entrypoint.sh:/scripts/entrypoint.sh  # Monta entrypoint.sh en el contenedor
      - ./modulos.txt:/scripts/modulos.txt      # Monta modulos.txt en el contenedor
      - ${CONF_PATH}:/opt/etc/odoo
      - ${DATA_PATH}:/opt/odoo/data
      - ${LOG_PATH}:/var/log/odoo
      - ${CUSTOM_ADDONS}:/mnt/extra-addons
      - ${SCRIPT_PATH}:/scripts
      - ${FILE_PATH}:/var/lib/odoo
    environment:
      - HOST=postgres
      - CUSTOM_ADDONS=${CUSTOM_ADDONS}
      - MAIN_MODULE=${MAIN_MODULE}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    networks:
      - odoo
